### ISSUE TITLE
factorio_item_production_input means "produced items" and vice versa

### ISSUE THREAD

**Issue by phdoerfler** [afex/graftorio#7]
I was a bit confused to find that `factorio_item_production_input` stands for the items **produced** by your factory while `factorio_item_production_output` denotes the items **consumed**. Is this intended?

**Comment by bradjshannon** [comment]
It is definitely counter-intuitive, compared to how we think about inputs/outputs in every other aspect of the game. But it makes sense if you think of input as being "into existence" or "into the universe."

**Comment by dragontuar** [comment]
or think of it this way the input is bringing items into a storage space from the factories and output is taking those items to be used

oh and with the mines the same thing their production is factory input

if @phdoerfler I am making things more problematic then ignore me then

**Comment by afex** [comment]
in this case, the input/output naming is based on the factorio API naming of `input_counts` and `output_counts` on `LuaFlowStatistics`

https://lua-api.factorio.com/latest/LuaFlowStatistics.html

**Comment by phdoerfler** [comment]
Thanks for the explanation. At least it's consistently confusing ;)
Still I think I'd very much welcome a "factorio_item_produced" and "factorio_item_consumed" (or something like this) that does away with this counter intuitiveness.
